import { IProductObject } from '@/interfaces'

export default [
	{
		colors: ['black'],
		material: ['Хлопок'],
		popularity: 0,
		price: 600,
		title: 'Футболка Phillip Plein',
		description: 'Чорна футболка Phillip Plein з черепом на спині, вироблена з хлопку.  ',
		globalCategory: 'maleClothes',
		category: 'tShirt',
		model: 'Phillip Plein череп',
		sizes: [ 'M', 'S'],
		images: [
			{
				color: ['black'],
				original: 'https://res.cloudinary.com/butterfly-project/image/upload/v2/products/Чорна футболка Phillip Plein__0__6890',
				thumbnail: 'https://res.cloudinary.com/butterfly-project/image/upload/v2/products/Чорна футболка Phillip Plein__0__6890',
			},
			{
				color: ['black'],
				original: 'https://res.cloudinary.com/butterfly-project/image/upload/v2/products/Чорна футболка Phillip Plein__1__6890',
				thumbnail: 'https://res.cloudinary.com/butterfly-project/image/upload/v2/products/Чорна футболка Phillip Plein__1__6890',
			},
			{
				color: ['black'],
				original: 'https://res.cloudinary.com/butterfly-project/image/upload/v2/products/Чорна футболка Phillip Plein__2__2971',
				thumbnail: 'https://res.cloudinary.com/butterfly-project/image/upload/v2/products/Чорна футболка Phillip Plein__2__2971',
			},
		],
		createdAt: '2023-04-18T19:06:18.939Z',
		updatedAt: '2023-04-20T12:13:55.462Z',
		__v: 0,
		id: '643eea2a80c5ab00476474c3',
	},
	{
		colors: ['blue'],
		material: ['Хлопок', 'Стрази'],
		popularity: 0,
		price: 650,
		title: 'Футболка Phillip Plein',
		description: 'Синя футболка Phillip Plein з черепом на спині. ',
		globalCategory: 'maleClothes',
		category: 'tShirt',
		model: 'Phillip Plein череп',
		sizes: ['L', ],
		images: [
			{
				color: ['blue'],
				original: 'Футболка Phillip Plein__0__3510',
				thumbnail: 'Футболка Phillip Plein__0__3510',
			},
			{
				color: ['blue'],
				original: 'Футболка Phillip Plein__1__3510',
				thumbnail: 'Футболка Phillip Plein__1__3510',
			},
			{
				color: ['blue'],
				original: 'Футболка Phillip Plein__2__3510',
				thumbnail: 'Футболка Phillip Plein__2__3510',
			},
		],
		createdAt: '2023-04-18T19:09:37.916Z',
		updatedAt: '2023-04-18T19:09:37.916Z',
		__v: 0,
		id: '643eeaf180c5ab00476474c6',
	},
	{
		colors: ['white'],
		material: ['Хлопок', 'Стрази'],
		popularity: 0,
		price: 650,
		title: 'Футболка Phillip Plein',
		description: 'Біла футболка Phillip Plein з черепом на спині. ',
		globalCategory: 'maleClothes',
		category: 'tShirt',
		model: 'Phillip Plein череп',
		sizes: ['XXL',  'XL', ],
		images: [
			{
				color: ['white'],
				original: 'Футболка Phillip Plein__0__2013',
				thumbnail: 'Футболка Phillip Plein__0__2013',
			},
			{
				color: ['white'],
				original: 'Футболка Phillip Plein__1__2013',
				thumbnail: 'Футболка Phillip Plein__1__2013',
			},
		],
		createdAt: '2023-04-18T19:11:39.407Z',
		updatedAt: '2023-04-18T19:11:39.407Z',
		__v: 0,
		id: '643eeb6b80c5ab00476474ca',
	},
] as IProductObject[]
